version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      # - 80:80
      - 81:81
      # - 82:82
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/test.conf:/etc/nginx/vhost/test.conf

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root1
      MONGO_INITDB_ROOT_PASSWORD: root2
    volumes:
      - ./mongodb/data/db:/data/db
    networks:
      - test
  node:
    build:
      context: ./node
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./node/api:/node/api
    networks:
      - test


  #  visit http://swarm-ip:8081, http://localhost:8081, or http://host-ip:8081 (as appropriate).
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   networks:
  #     - test

networks:
  test:
    driver: bridge
